### PR TITLE
Bugfix/v3.10.x/1058 added read write timeout to patchkit network

### PR DESCRIPTION
**Pull request by Dzejkop**

### CODE REVIEW

**Comment by Dzejkop** [comment]
@witcher112  according to [MSDN](https://msdn.microsoft.com/library/system.net.httpwebrequest.readwritetimeout(v=vs.110).aspx)

> "Specifically, the ReadWriteTimeout property controls the time-out for the Read method, which is used to read the stream returned by the GetResponseStream method"

**Comment by Dzejkop** [comment]
It's partially fixing the issue. With this fix the Patcher won't freeze for 5 minutes, instead it'll crash the download and (hopefully) retry.

**Comment by genail** [comment]
@Dzejkop did you test it with the script that I've provided?

**Comment by witcher112** [comment]
Never mind, it was my fault of wrong understanding of this issue. The fix is all right.

**Comment by Dzejkop** [comment]
@genail yes I did to the extent of the download timing out and nothing more

**Comment by genail** [comment]
@Dzejkop just a changelog and we can proceed.

**Pull request merged**
